---
title: States of Mind
timezone: UTC
collections:
  education-programme:
    title: Education Programme
    output: true
    Introduction: This is the introduction to the education programme
    Year: 2020
  handbook:
    title: Handbook
    output: true
    permalink: "/handbook/:path"
  posts:
    title: Posts
    output: true
  quiz:
    title: Quiz
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _uploads
  values:
    image: true
- scope:
    path: education-programme
  values:
    Slides:
    - Template:
      Title:
      Image:
      Description:
      Graphic Image:
      Audio url:
      Video Url:
      Credit:
      Links:
      - Link Url:
      Quote:
      Quote Credit:
      Slide Colour:
- scope:
    path: quiz
  values:
    permalink: /:collection/:path
    Quiz type:
    Question:
    Choice:
    Answers:
    - Answer:
      True/False:
    Education programme:
    slide:
    layout: quiz
Cover Image:
Cover Colour:
email: hello@benlongdendesign.co.uk
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url:
sass:
  sass_dir: _sass
  style: compressed
twitter_username: benlongden
github_username: blongden73
theme: minima
plugins:
- jekyll-feed
