---
title: StatesofMind
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _uploads
  values:
    image: true
email: hello@benlongdendesign.co.uk
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
sass:
  sass_dir: _sass
  style: compressed
twitter_username: benlongden
github_username: blongden73
theme: minima
plugins:
- jekyll-feed
